### ISSUE TITLE
Unicode for "Arabic ligature radi Allaahu anhum" did'nt show correctly

### ISSUE THREAD

**Issue by atmorojo** [sywprabu/Ilm-Translation-Project#3]
Expectation:
Unicode FD43 that is supposed to be Arabic ligature for "radi Allaahu anhum".

Problem:
Instead it renders as a hexagon with a tilted cross (x) in it.

Possible cause:
Font problem. Could be just my issue with my Firefox settings. Maybe we should use a font that supports this so people without proper browser/system setting could experience the site as it is supposed to be.

**Comment by atmorojo** [comment]
Btw I checked [Amiri](https://fonts.google.com/specimen/Amiri) but it didn't render U+FD43 too. Will check KFGQPC Uthman later.

Would love to hear your thoughts on this @sywprabu.

**Comment by atmorojo** [comment]
LOL. False alarm. It's fontconfig's problem on my end and there's no possible fixing it here.

Closing.

**Comment by sywprabu** [comment]
Alhamdulillah it sorted out well.
