### ISSUE TITLE
Unwanted share buttons on top-right of page

### ISSUE THREAD

**Issue by sywprabu** [sywprabu/Ilm-Translation-Project#4]
###  Issue
There are buttons that linked to some websites. This is unwanted since it hinders simplicity and "clean page" principality. It needs to be removed.

### Problem
I can't seem to find any file that contains these buttons. Your guidance @atmorojo on this matter will be appreciated.

**Comment by atmorojo** [comment]
Try this: [gitbook-sharing.json.tpl](https://github.com/sywprabu/Ilm-Translation-Project/blob/main/_includes/gitbook-sharing.json.tpl)

Maybe set everything to false?

**Comment by sywprabu** [comment]
Will do when I am available.

**Comment by sywprabu** [comment]
[gitbook-sharing.json.tpl](https://github.com/sywprabu/Ilm-Translation-Project/blob/main/_includes/gitbook-sharing.json.tpl) is indeed the right file. But the last share button still remains. Will it be okay if I comment out the entire file?

And additionally how do I comment in this type of file?

**Comment by atmorojo** [comment]
There's no possible way to comment it. But I changed the name of the variable needed to create the buttons so the script unable to find whatever it is trying to find. Decided not to delete it just in case we need it later.

**Comment by sywprabu** [comment]
Agree on changing the name in case of potential future usability. It's done then, _alhamdulillah_. I'm closing this issue.
