### ISSUE TITLE
Table of Content translation

### ISSUE THREAD

**Issue by sywprabu** [sywprabu/Ilm-Translation-Project#5]
We should start again from translating the Table of Content.

**Comment by sywprabu** [comment]
I have translated it. But it still does not act as a functional TOC. I do not know how to make it that way. I believe that is a task for another issue. So I am closing this one.

**Comment by atmorojo** [comment]
Sorry I just realized there's a notification here. My intention was for us having a to-do list for what we're about to work on. We can start using your work as filenames, and let Jekyll generate the menu for us. I'll check later tonight and see what I can do to make some progress.

**Comment by sywprabu** [comment]
Nice. And maybe when the toc functions as intended we can merge it with the main branch. Since this issue is about toc translation. Let us move the discussion to its own issue here https://github.com/sywprabu/Ilm-Translation-Project/issues/8
